Create table family_table
(
    id                 integer generated by default as identity
        primary key,
    family_last_name   varchar(255),
    father_name        varchar(255),
    mother_name        varchar(255)
);

INSERT INTO family_table (family_last_name, father_name, mother_name) VALUES
('Smith', 'John Smith', 'Jane Smith'),
('Johnson', 'Michael Johnson', 'Emily Johnson'),
('Williams', 'Robert Williams', 'Linda Williams'),
('Nikan', 'Ella Nikan', 'Linda Williams'),
('Mark', 'Robert Mark', 'Elsa Villa');